### ISSUE TITLE
Throws an error

### ISSUE THREAD

**Issue by mgorabbani** [vinnyoodles/react-native-socket-io-example#1]
`react-native-socket-io-example-master/node_modules/mongodb/lib/mongo_client.js:224
          throw err
          ^`

**Comment by wenkesj** [comment]
Do you have mongodb daemon running? @mgorabbani

**Comment by mgorabbani** [comment]
Nope!! now i understand!

**Comment by jamesbaker1** [comment]
How do you run the mongoldb daemon properly?

**Comment by vincent144** [comment]
[Instructions on getting MongoDB running](https://docs.mongodb.com/manual/installation/)
