### ISSUE TITLE
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

### ISSUE THREAD

**Issue by giantss** [vinnyoodles/react-native-socket-io-example#15]
environment: mac、ios

When sending a message, it will throw an exception
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

![image](https://user-images.githubusercontent.com/13778798/37012118-0096d0aa-212e-11e8-9bcb-73d8913a358d.png)

**Comment by vincent144** [comment]
You have to run an instance of MongoDB locally on port 27017.

**Comment by vincent144** [comment]
See #1

**Comment by jorgerodriguez434** [comment]
I still don't understand how to solve this
