### ISSUE TITLE
Error: Document is not defined on ReactNative 

### ISSUE THREAD

**Issue by rexonms** [vinnyoodles/react-native-socket-io-example#2]
I am getting document is not defined. Following is how I implemented it. 
Image: http://i66.tinypic.com/2n6swp3.png

     

    import React, { Component } from 'react'
    import { View, Text, Image, ScrollView } from 'react-native'
    import SocketIOClient from 'socket.io-client';

    class Game extends Component {
        constructor(props) {
            super(props)

            this.socket = SocketIOClient('http://localhost:8008');
            this.socket.on('message', this.onReceivedMessage);
    }
    // Event listeners
    /**
     * When the server sends a message to this.
     */
    onReceivedMessage(messages) {
        alert(message)
    }
    render() {
        console.log('rerendered!!!!')
        return(
            <View style={{flex:1}}>
               ....
            </View>
        )
      }
    }
    export default Game

**Comment by eiosca** [comment]
Hi, follow this instruction, it work's for me: https://medium.com/@ekryski/how-to-actually-use-socket-io-in-react-native-39082d8d6172#.emqahhs7g
