### ISSUE TITLE
Unknown named module:'xmlhttprequest-ssl'

### ISSUE THREAD

**Issue by ycpatel813** [vinnyoodles/react-native-socket-io-example#4]
Hi 
I found this error when I try to run a demo.
I have completely installed all node modules, but I found this error.

I have googled for this error and find a solution that XMLHttpRequest work fine in IOS but my platform is Android- 5.0.1.

Thank you.

**Comment by bpsourav21** [comment]
I have just replaced `import SocketIOClient from  'socket.io-client'; ` to ` import SocketIOClient from  'socket.io-client/dist/socket.io'; ` on client side code and its working

**Comment by vincent144** [comment]
Duplicate #7
